// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
alias(libs.plugins.android.application) apply false
}

// Redirigir la carpeta build del proyecto raíz a /tmp/ai_rebellion
layout.buildDirectory.set(file("/tmp/ai_rebellion/root-build"))