

[build]
rustflags = [
    "-C", "relocation-model=pic",
    "-C", "link-arg=-Wl,-z,max-page-size=16384",
    "-C", "link-arg=-Wl,-z,common-page-size=16384",
    "-C", "link-arg=-landroid",
    "-C", "link-arg=-llog"
]

